[package]
name = "delegate-project-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
openai-api-rs = "6.0.3"
reqwest = { version = "0.12.15", features = ["blocking"] }
tokio = { version = "1.44.2", features = ["full"] }
warp = { version = "0.3.7", features = ["tls"] }
